name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
    commit-matcher:
      - '/^feat:/'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
    commit-matcher:
      - '/^fix:/'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
    commit-matcher:
      - '/^docs:/'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
    commit-matcher:
      - '/^chore:/'
      - '/^refactor:/'
  - title: 'Other'
    commit-matcher:
      - '/.+/'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

include-labels:
  - 'feature'
  - 'enhancement'
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'documentation'
  - 'maintenance'

include-commits: true
include-pull-requests: true

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What's Changed
  $CHANGES
  
  ## 👥 Contributors
  $CONTRIBUTORS