# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]

  - repo: local
    hooks:
      - id: ruff-format
        name: Formatting
        entry: poetry run ruff format
        language: system
        types: [ python ]
        args: [ "--config", "pyproject.toml" ]
        pass_filenames: true

      - id: ruff-lint
        name: Linting
        entry: poetry run ruff check
        language: system
        types: [ python ]
        args: [ "--config", "pyproject.toml" ]
        pass_filenames: true
        exclude: tests

      - id: mypy-type-check
        name: Type Checking
        entry: poetry run mypy
        language: system
        types: [ python ]
        args: [ "--config", "pyproject.toml" ]
        pass_filenames: true
