# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Formatting
        entry: poetry run ruff format
        language: system
        types: [ python ]
        args: [ "--config", "pyproject.toml" ]
        pass_filenames: true
      - id: ruff-lint
        name: Linting
        entry: poetry run ruff check
        language: system
        types: [ python ]
        args: [ "--config", "pyproject.toml" ]
        pass_filenames: true
