name: "Setup Environment"
description: "Sets up Python, uv, and dependencies with caching"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.14"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv sync
