# .github/actions/setup-env/action.yml
name: 'Setup Python Environment'
description: 'Sets up Python environment with Poetry and installs dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Restore Poetry Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ~/.poetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: |
        poetry install
