name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Call Setup Workflow
        uses: ./.github/workflows/setup.yml

      - name: Run Ruff Linting
        run: |
          poetry run ruff check --config pyproject.toml src/
