name: Format

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Call the reusable setup workflow without @branch
      - name: Call Setup Workflow
        uses: ./.github/workflows/setup.yml

      # Run Ruff formatting after setup
      - name: Run Ruff Formatting
        run: |
          poetry run ruff format --config pyproject.toml src/
