name: Format

on:
  workflow_call: # Allows this workflow to be called by other workflows

jobs:
  format:
    runs-on: ubuntu-latest
    needs: setup  # Dependency on setup job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Poetry Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Run Ruff Formatting
        run: |
          poetry run ruff format --config pyproject.toml src/
