name: Format

on:
  push:
    branches:
      - '*'  # Trigger on all branches
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Setup Python and Poetry
        uses: ./.github/actions/common/setup-python-poetry.yml
        with:
          python-version: '3.12'

      - name: Run Ruff Formatting
        run: |
          poetry run ruff format --config pyproject.toml src/
