name: Initialize Repository

on:
  push:
    branches:
      - main

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for initial commit
        id: check_initial_commit
        run: |
          if git rev-list --count HEAD | grep -q '^0$'; then
            echo "This is the initial commit."
            echo "is_initial=true" >> $GITHUB_ENV
          else
            echo "This repository already has commits."
            echo "is_initial=false" >> $GITHUB_ENV
          fi

      - name: Set Repository Name and Description
        if: env.is_initial == 'true'  # Only run if it's the initial commit
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          REPO_DESC="${{ github.event.repository.description }}"
          VERSION="0.0.1"

          # Update the pyproject.toml with the repository name and description
          sed -i "s/^name = .*/name = \"$REPO_NAME\"/" pyproject.toml
          sed -i "s/^description = .*/description = \"$REPO_DESC\"/" pyproject.toml
          sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml

      - name: Commit changes
        if: env.is_initial == 'true'  # Only run if it's the initial commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pyproject.toml
          git commit -m "chore: initialize repository"
          
          # Push to main
          git push origin main

          # Create develop branch and push
          git checkout -B develop
          git push origin develop --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
