name: CI and Release

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  format:
    needs: setup
    uses: ./.github/workflows/format.yml