name: CI and Release

on:
  push:
    branches:
      - '*'  # Trigger on all branches
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  format:
    uses: ./.github/workflows/format.yml
    needs: setup  # Ensure setup job has succeeded

  lint:
    uses: ./.github/workflows/lint.yml
    needs: format  # Ensure format job has succeeded

  type-check:
    uses: ./.github/workflows/type-check.yml
    needs: format  # Ensure format job has succeeded

  test:
    uses: ./.github/workflows/test.yml
    needs: setup  # Ensure setup job has succeeded

  create_release:
    uses: ./.github/workflows/create-release.yml
    needs: [ lint, type-check, test ]  # Ensure lint, type-check, and test jobs have succeeded
    if: github.ref == 'refs/heads/main'  # Only run on main branch
