name: Main Workflow

on:
  push: # Trigger on push events to any branch
  pull_request: # Trigger on pull request events to any branch
    branches:
      - '**' # Matches all branches

jobs:
  call-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Format Workflow
        uses: ./.github/workflows/format.yml  # Call the format workflow
