name: CI and Release

on:
  push:
    branches:
      - '*'  # Trigger on all branches
  pull_request:

jobs:
  format:
    uses: ./.github/setup


#  lint:
#    uses: ./.github/workflows/lint.yml
#
#  type-check:
#    uses: ./.github/workflows/type-check.yml
#
#  test:
#    uses: ./.github/workflows/test.yml
#
#  create_release:
#    uses: ./.github/workflows/create-release.yml
#    needs: [ format, lint, type-check, test ]  # Run after all checks
#    if: github.ref == 'refs/heads/main'
