name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    needs:
      - Format, Lint, and Type Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from pyproject.toml
        id: read_version
        run: |
          # Extract the version using grep from pyproject.toml
          VERSION=$(grep '^version =' pyproject.toml | sed -E 's/version = "(.+)"/\1/')
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: "Release generated automatically from pyproject.toml version."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
