name: Create Release

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Ruff Formatting
        run: |
          poetry run ruff format --config pyproject.toml .

  lint:
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Ruff Linting
        run: |
          poetry run ruff check --config pyproject.toml .

  type-check:
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Mypy Type Checking
        run: |
          poetry run mypy --config-file pyproject.toml .

  create_release:
    runs-on: ubuntu-latest
    needs: [ format, lint, type-check ]  # Ensure the lint job has succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Read version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(poetry version --short)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
