name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Call Setup Workflow
        uses: ./.github/workflows/setup.yml

      - name: Run Unit Tests
        run: |
          poetry run pytest
