name: Lint

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    needs: setup  # Ensure setup job has succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Restore Poetry Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Run Unit Tests
        run: |
          poetry run pytest