name: Type Check

on:
  workflow_call:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Call Setup Workflow
        uses: ./.github/workflows/setup.yml

      - name: Run Mypy Type Checking
        run: |
          poetry run mypy --config-file pyproject.toml src/
